scenario list: ['Left Turn (AV goes straight)']  # the order of scenarios should be the same as test order

AV:
  speed: [5]  # AV speed when there are no challengers
  sumo route name: 'AV_route'  # refer to sumo route
  start lane id: 'EG_18_12_171_0'  # refer to sumo route
  length: 5
  width: 2

BV:
  num: 1
  scenarios: [['Left Turn (AV goes straight)']]
  start lane id: ['EG_4_1_20_0']
  length: [5]
  width: [2]
  init position: [0]

VRU:
  num: 0
  scenarios: []
  start lane id: []
  length: []
  width: []

scenario info:
  Left Turn (AV goes straight):
    AV:
      start ind: 10
      conflict ind: 194
      end ind: 240
    challenger:
      start ind: 20
      init ind: 158  # 134
      conflict ind: 171
      end ind: 210

    turning offset: 0
    turning radius: 15

    max acceleration: [2.87, 2.7323037241440984, 1.852909388992379, 0.3356996843802441]
    min acceleration: [-7.06, -4.241907650382408, -2.314763578693004, -0.4168063610293639]
    acceleration reaction time: [1.5, 1.5, 1.5, 1.5]
    deceleration reaction time: [1.5, 1.5, 1.5, 1.5]
    min initial distance: 1
    max initial distance: 50
    min AV speed: 3
    max AV speed: 15
    min BV speed: 3
    max BV speed: 8
    distance resolution:
      low: 2
      mid: 1
      high: 0.5
    speed resolution:
      low: 2
      mid: 1
      high: 0.5

lane width: 3.5
