scenario list: ['Left Turn (AV turns left)']  # the order of scenarios should be the same as test order

AV:
  speed: [3.61]  # AV speed when there are no challengers
  sumo route name: 'AV_route'  # refer to sumo route
  start lane id: 'EG_4_1_20_0'  # refer to sumo route
  length: 5
  width: 2

BV:
  num: 1
  scenarios: [['Left Turn (AV turns left)']]
  start lane id: ['EG_8_3_1_0']
  length: [5]
  width: [2]
  init position: [0]

VRU:
  num: 0
  scenarios: []
  start lane id: []
  length: []
  width: []

scenario info:
  Left Turn (AV turns left):
    AV:
      start ind: 8
      conflict ind: 171
      end ind: 195
    challenger:
      start ind: 10
      init ind: 146
      conflict ind: 194
      end ind: 240

    turning offset: 10
    turning radius: 15
    intersection length: 42

    max acceleration: [2.87, 2.7273669579837585, 1.9572837255311968, 0.3764395918938628]
    min acceleration: [-7.06, -4.1828291751628, -2.368826049843337, -0.3266070381432803]
    acceleration reaction time: [1.5, 1.5, 1.5, 1.5]
    deceleration reaction time: [1.5, 1.5, 1.5, 1.5]
    min initial distance: 1
    max initial distance: 60
    min AV speed: 3
    max AV speed: 10
    min BV speed: 1
    max BV speed: 10
    distance resolution:
      low: 2
      mid: 1
      high: 0.5
    speed resolution:
      low: 2
      mid: 1
      high: 0.5

lane width: 3.5
